name: 🚀 Deploy Next.js to Hostland

on:
  push:
    branches:
      - main # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js with environment variables
      - name: Build Next.js with env
        run: |
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env.production
          echo "CONTACT_EMAIL=${{ secrets.CONTACT_EMAIL }}" >> .env.production
          npm run build

      # 5️⃣ List files for debugging before deploy
      - name: List local project files
        run: |
          echo "== ROOT =="
          ls -lah
          echo "== .next =="
          ls -lah .next || true
          echo "== public =="
          ls -lah public || true

      # 6️⃣ Deploy built files to Hostland via SCP (with debug)
      - name: Deploy built files to Hostland
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTLAND_HOST }}
          username: ${{ secrets.HOSTLAND_USER }}
          port: ${{ secrets.HOSTLAND_PORT }}
          key: ${{ secrets.HOSTLAND_SSH_KEY }}
          passphrase: ${{ secrets.HOSTLAND_SSH_PASSPHRASE }}
          source: "./.next/ public server.js package.json"
          target: "/home/${{ secrets.HOSTLAND_USER }}/cms.housebetongroup.ru/projects/cms-housebetongroup-next"
          debug: true

      # 7️⃣ Verify files on the server
      - name: Check files on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTLAND_HOST }}
          username: ${{ secrets.HOSTLAND_USER }}
          key: ${{ secrets.HOSTLAND_SSH_KEY }}
          port: ${{ secrets.HOSTLAND_PORT }}
          script: |
            echo "== PROJECT DIR =="
            ls -lah /home/${{ secrets.HOSTLAND_USER }}/cms.housebetongroup.ru/projects/cms-housebetongroup-next
            echo "== .next =="
            ls -lah /home/${{ secrets.HOSTLAND_USER }}/cms.housebetongroup.ru/projects/cms-housebetongroup-next/.next || true

      # 8️⃣ Install production dependencies on Hostland
      - name: Install production dependencies
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTLAND_HOST }}
          username: ${{ secrets.HOSTLAND_USER }}
          key: ${{ secrets.HOSTLAND_SSH_KEY }}
          port: ${{ secrets.HOSTLAND_PORT }}
          script: |
            /home/${{ secrets.HOSTLAND_USER }}/cms.housebetongroup.ru/node/v22.4.1/bin/node \
              /home/${{ secrets.HOSTLAND_USER }}/cms.housebetongroup.ru/node/v22.4.1/lib/node_modules/npm/bin/npm-cli.js install --omit=dev

      # 9️⃣ Restart your app on Hostland (Passenger)
      - name: Restart app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTLAND_HOST }}
          username: ${{ secrets.HOSTLAND_USER }}
          key: ${{ secrets.HOSTLAND_SSH_KEY }}
          port: ${{ secrets.HOSTLAND_PORT }}
          script: |
            touch /home/${{ secrets.HOSTLAND_USER }}/cms.housebetongroup.ru/projects/cms-housebetongroup-next/tmp/restart.txt
